---
name: myfirstghpj
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: git clone stage
        uses: actions/checkout@v3
      - name: install stage
        run: |
          sudo apt-get update 
          sudo apt-get install docker.io -y 
          sudo usermod -aG docker $USER
          docker
