---
name: myfirstghpj
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: git clone stage
        uses: actions/checkout@v3
      - name: install stage
        run: |
          #sudo apt-get install docker.io -y 
          wget https://www.free-css.com/assets/files/free-css-templates/download/page291/atlas.zip
          ls 
          sudo usermod -aG docker $USER
          docker
