name: myfirstghpj
on: [push]
jobs:
  name: install
    runs-on: ubuntu-latest
    steps:
      - name: git clone stage
        uses: actions/checkout@v3
      - name: install stage
        run: |
         apt-get update 
         apt-get install docker.io -y
         docker
         